name: Continuous builds

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:

    - uses: actions/checkout@v3
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install tox tox-gh-actions

    - name: List packages so far
      run: |
        pip list

    - name: Run tests
      run: |
          tox

    - name: Run example tests
      run: |
          pip install -r ./requirements_dev.txt
          pip install .
          # uses pp, which is not available for py3
          # python3 ./tests/evaluator_tests.py
          python3 ./tests/example_tests.py
          python3 ./tests/observer_tests.py
          # intermittently fails
          python3 ./tests/operator_tests.py || exit 0
          python3 ./tests/supplemental_tests.py
